ALTER TABLE idea
    ADD COLUMN IF NOT EXISTS one_liner TEXT,
    ADD COLUMN IF NOT EXISTS problems TEXT,
    ADD COLUMN IF NOT EXISTS revenue_model TEXT,
    ADD COLUMN IF NOT EXISTS strengths TEXT,
    ADD COLUMN IF NOT EXISTS risks TEXT;
